# -*- coding: utf-8 -*-
"""Shortage_identification_kz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgASWG6J5hzbkcufyBJQ9smFHvgJA9Nq

# Set Up
"""

! pip install datasets

#from google.colab import drive
import re
import openai
import time
from tqdm import tqdm

import random
from random import shuffle

import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from datasets import Dataset
from transformers import AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments, Trainer
from peft import LoraConfig, get_peft_model
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import os
os.environ["WANDB_DISABLED"] = "true"

from google.colab import drive
drive.mount('/content/drive')

file_path1 = "/content/drive/MyDrive/Weightloss/1000samples.xlsx"
file_path2 = '/content/drive/MyDrive/Weightloss/df_nokey_results.xlsx'
df1 = pd.read_excel(file_path1,index_col = 0)
df2 = pd.read_excel(file_path2)
df3 = df1[df1['yc_label'].notna()]
df3_selected = df3[['text', 'yc_label', 'comment']].rename(columns={'yc_label': 'label', 'comment': 'reason'})

# count the word occurance

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Initialize CountVectorizer
vectorizer = CountVectorizer(stop_words='english')

# Fit and transform the text column
word_matrix = vectorizer.fit_transform(df3_selected['text'])

# Convert the word matrix to a DataFrame
word_count_df = pd.DataFrame(
    word_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)

# Sum the counts for each word across all rows
word_counts = word_count_df.sum(axis=0).sort_values(ascending=False)

# Convert to DataFrame for better readability
word_count_summary = word_counts.reset_index()
word_count_summary.columns = ['Word', 'Count']

# Display the result
print(word_count_summary[:50])

import random
from collections import Counter
from itertools import chain

def swap_words_in_corpus(corpus, target_words, swap_percentage=0.3, stop_words=None):
    """
    Swaps target words across the entire corpus with random words based on a percentage,
    ensuring no new stop words are introduced.

    Args:
        corpus (list of str): List of texts (strings) in the corpus.
        target_words (list): Words to target for swapping.
        swap_percentage (float): Percentage of target words to swap.
        stop_words (set): Set of stop words to ignore in replacements.

    Returns:
        list of str: Modified corpus with words swapped.
    """
    if stop_words is None:
        stop_words = {"the", "is", "a", "an", "and", "or", "in", "of", "to", "on", "at", "with", "for", "by", "it"}

    # Flatten the corpus into a list of words
    all_words = list(chain.from_iterable(text.split() for text in corpus))

    # Filter out stop words from the corpus for replacements
    filtered_corpus_words = [word for word in all_words if word.lower() not in stop_words]

    # Debugging: Check filtered corpus
    print("Filtered Corpus Words (Replacements):", filtered_corpus_words)

    # Count occurrences of target words across the entire corpus
    word_counts = Counter(all_words)
    target_word_counts = {word: word_counts[word] for word in target_words if word in word_counts}

    # Debugging: Check target word counts
    print("Target Word Counts:", target_word_counts)

    # Calculate total swaps needed for each target word
    total_swaps = {word: max(1, int(count * swap_percentage)) if count > 0 else 0 for word, count in target_word_counts.items()}

    # Debugging: Check total swaps per word
    print("Total Swaps Per Word:", total_swaps)

    # Perform swaps in the corpus
    for word, num_swaps in total_swaps.items():
        if num_swaps == 0:
            print(f"No swaps needed for '{word}'.")
            continue  # Skip if no swaps are needed

        # Find all occurrences of the target word across the corpus
        occurrences = [(text_idx, word_idx)
                       for text_idx, text in enumerate(corpus)
                       for word_idx, w in enumerate(text.split()) if w == word]

        # Debugging: Check occurrences of the target word
        print(f"Occurrences of '{word}':", occurrences)

        # Randomly select the occurrences to swap
        if len(occurrences) > 0:
            swap_indices = random.sample(occurrences, min(num_swaps, len(occurrences)))

            # Debugging: Check selected indices for swapping
            print(f"Selected Indices for Swapping '{word}':", swap_indices)

            # Replace the target word with a random non-stop-word from the corpus
            for text_idx, word_idx in swap_indices:
                words = corpus[text_idx].split()
                replacement = random.choice(filtered_corpus_words)
                while replacement in target_words:  # Avoid replacing with another target word
                    replacement = random.choice(filtered_corpus_words)
                words[word_idx] = replacement
                corpus[text_idx] = " ".join(words)
        else:
            print(f"No occurrences of '{word}' found.")

    return corpus

corpus = list(df3_selected['text'])

target_words = ["shortage", "short", "available"]
stop_words = {"of", "the", "to", "a", "on", "it", "in", "is", "and", "or", "with"}

# Call the function
modified_corpus = swap_words_in_corpus(corpus, target_words, swap_percentage=0.3, stop_words=stop_words)
df3_selected['text'] = modified_corpus



"""## no key words"""

#drive.mount('/content/drive')
#file_path1 = '../1000samples_0114.csv'
file_path2 = '/content/drive/MyDrive/Weightloss/df_nokey_results.xlsx'

#df1 = pd.read_csv(file_path1,index_col = 0)
df2 = pd.read_excel(file_path2)
#df3 = df1[df1['yc_label'].notna()]
#df3_selected = df3[['text', 'yc_label', 'comment']].rename(columns={'yc_label': 'label', 'comment': 'reason'})
df2_selected = df2[['text', 'Shortage2', 'Cue Words2']].rename(columns={'Shortage2': 'label', 'Cue Words2': 'reason'})
data = pd.concat([df3_selected, df2_selected], ignore_index=True)
#data = df3_selected

data['label'] = data['label'].astype(str).str.upper().str.strip()
data['label'] = data['label'].replace({'1.0': 'YES', '0.0': 'NO', '1': 'YES', '0': 'NO'})
valid_labels = {'YES', 'NO'}
data['label'] = data['label'].apply(lambda x: x if x in valid_labels else None)
data['label'] = data['label'].map({'YES': 1.0, 'NO': 0.0})
data = data.sample(frac=1).reset_index(drop=True)

data

MODEL_NAME = "FacebookAI/roberta-base"
BATCH_SIZE = 16
EPOCHS = 20
LEARNING_RATE = 2e-5

train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    data["text"].tolist(), data["label"].tolist(), test_size=0.4, random_state=42)
val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts, temp_labels, test_size=0.5, random_state=42)

# Tokenizer processing
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_function(texts):
    return tokenizer(texts, padding="max_length", truncation=True, max_length=128, return_tensors="pt")

train_encodings = tokenize_function(train_texts)
val_encodings = tokenize_function(val_texts)
test_encodings = tokenize_function(test_texts)

#  Hugging Face Dataset
train_dataset = Dataset.from_dict({
    "input_ids": train_encodings["input_ids"],
    "attention_mask": train_encodings["attention_mask"],
    "labels": torch.tensor(train_labels, dtype=torch.long)
})

val_dataset = Dataset.from_dict({
    "input_ids": val_encodings["input_ids"],
    "attention_mask": val_encodings["attention_mask"],
    "labels": torch.tensor(val_labels, dtype=torch.long)
})

test_dataset = Dataset.from_dict({
    "input_ids": test_encodings["input_ids"],
    "attention_mask": test_encodings["attention_mask"],
    "labels": torch.tensor(test_labels, dtype=torch.long)
})

#  Transformer
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

#
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=LEARNING_RATE,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    num_train_epochs=EPOCHS,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    push_to_hub=False,
    report_to="none"  #  WandB
)

#
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    acc = accuracy_score(labels, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average="binary")
    return {"accuracy": acc, "precision": precision, "recall": recall, "f1": f1}

#
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

trainer.train()

#
##model.save_pretrained("./finetuned_model")
##tokenizer.save_pretrained("./finetuned_model")

#
eval_results = trainer.evaluate(test_dataset)
print(eval_results)  #

#
print(f"Test Accuracy: {eval_results.get('eval_accuracy', 0.0):.4f}")
print(f"Test Precision: {eval_results.get('eval_precision', 0.0):.4f}")
print(f"Test Recall: {eval_results.get('eval_recall', 0.0):.4f}")
print(f"Test F1 Score: {eval_results.get('eval_f1', 0.0):.4f}")

import torch
import torch.nn.functional as F
import pandas as pd
import numpy as np
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.model_selection import train_test_split
from datasets import Dataset
from transformers import AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments, Trainer
from transformers import EarlyStoppingCallback

# Parameters
MODEL_NAME = "roberta-base"
BATCH_SIZE = 16
EPOCHS = 20
LEARNING_RATE = 3e-5
WARMUP_STEPS = 500

# Convert labels to numpy arrays
train_labels = np.array(train_labels).astype(int)
val_labels = np.array(val_labels).astype(int)
test_labels = np.array(test_labels).astype(int)

# Compute class weights
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(train_labels),
    y=train_labels
)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float)

# Tokenizer preprocessing
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_function(texts):
    return tokenizer(texts, padding="max_length", truncation=True, max_length=512, return_tensors="pt")

train_encodings = tokenize_function(train_texts)
val_encodings = tokenize_function(val_texts)
test_encodings = tokenize_function(test_texts)

# Hugging Face Dataset
train_dataset = Dataset.from_dict({
    "input_ids": train_encodings["input_ids"],
    "attention_mask": train_encodings["attention_mask"],
    "labels": torch.tensor(train_labels, dtype=torch.long)
})

val_dataset = Dataset.from_dict({
    "input_ids": val_encodings["input_ids"],
    "attention_mask": val_encodings["attention_mask"],
    "labels": torch.tensor(val_labels, dtype=torch.long)
})

test_dataset = Dataset.from_dict({
    "input_ids": test_encodings["input_ids"],
    "attention_mask": test_encodings["attention_mask"],
    "labels": torch.tensor(test_labels, dtype=torch.long)
})

# Load the model
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

# Freeze embedding layers and first 8 encoder layers for RoBERTa
for param in model.roberta.embeddings.parameters():
    param.requires_grad = False

for i, layer in enumerate(model.roberta.encoder.layer):
    if i < 8:  # Freeze first 8 layers
        for param in layer.parameters():
            param.requires_grad = False

# Training Arguments
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=LEARNING_RATE,
    warmup_steps=WARMUP_STEPS,
    lr_scheduler_type="linear",
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    num_train_epochs=EPOCHS,
    weight_decay=0.02,
    logging_dir="./logs",
    logging_steps=20,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    save_total_limit=3
)


from transformers import Trainer

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        """
        Override the compute_loss method to use class weights on the correct device.

        Args:
            model: The model being trained.
            inputs: A dictionary of input tensors.
            return_outputs: Whether to return the model outputs along with the loss.
            **kwargs: Additional arguments that may be passed by the Trainer.

        Returns:
            Loss value and optionally model outputs.
        """
        labels = inputs.pop("labels")  # Extract labels
        outputs = model(**inputs)      # Forward pass
        logits = outputs.logits       # Model predictions

        # Move class weights to the same device as logits
        device = logits.device
        weighted_loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights_tensor.to(device))

        # Compute weighted loss
        loss = weighted_loss_fn(logits, labels)

        # Return outputs if required
        return (loss, outputs) if return_outputs else loss

# Compute Metrics
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    probs = torch.softmax(torch.tensor(logits), dim=-1).numpy()
    predictions = (probs[:, 1] > 0.5).astype(int)

    acc = accuracy_score(labels, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average="binary", zero_division=1)

    return {"accuracy": acc, "precision": precision, "recall": recall, "f1": f1}

from transformers import EarlyStoppingCallback

# Trainer with Early Stopping
trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]  # Stop if no improvement for 3 evaluations
)

# Train the model
trainer.train()

# Save the fine-tuned model and tokenizer
model.save_pretrained("./finetuned_model")
tokenizer.save_pretrained("./finetuned_model")

# Evaluate on the test dataset
eval_results = trainer.evaluate(test_dataset)
print(eval_results)

# Print test metrics
print(f"Test Accuracy: {eval_results.get('eval_accuracy', 0.0):.4f}")
print(f"Test Precision: {eval_results.get('eval_precision', 0.0):.4f}")
print(f"Test Recall: {eval_results.get('eval_recall', 0.0):.4f}")
print(f"Test F1 Score: {eval_results.get('eval_f1', 0.0):.4f}")

model_save_path = "finetuned_model/final_model"

# 保存模型
model.save_pretrained(model_save_path)
tokenizer.save_pretrained(model_save_path)

#print(f"✅ Google Drive: {model_save_path}")



"""labeling"""

from transformers import AutoModelForSequenceClassification, AutoTokenizer

model_load_path = "finetuned_model/final_model"

model = AutoModelForSequenceClassification.from_pretrained(model_load_path)
tokenizer = AutoTokenizer.from_pretrained(model_load_path)

drive_save_path = "results/predicted_results.csv"

def predict_new_data(model_path, tokenizer_path, batch_size=16, device=None):
    # Set device (default to CUDA if available)
    device = device or ("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
    model = AutoModelForSequenceClassification.from_pretrained(model_path)
    model.to(device)  # Move model to the device
    model.eval()

    # Load data
    comment = pd.read_csv("../df_comments.csv")
    sub = pd.read_csv("../df_submissions.csv")

    # Normalize text
    comment["text1"] = comment["text"].astype(str).str.lower()
    sub["text1"] = sub["text"].astype(str).str.lower()

    # Merge data
    merged_df = pd.concat([comment, sub], ignore_index=True)
    texts = merged_df["text1"].dropna().tolist()

    predictions = []
    for i in tqdm(range(0, len(texts), batch_size), desc="Predicting Batches"):
        batch_texts = texts[i:i+batch_size]
        encodings = tokenizer(batch_texts, padding=True, truncation=True, max_length=512, return_tensors="pt").to(device)

        with torch.no_grad():
            outputs = model(**encodings)
            batch_predictions = torch.argmax(outputs.logits, axis=-1).cpu().numpy()  # Move back to CPU for numpy
            predictions.extend(batch_predictions)

    merged_df["predicted_label"] = predictions
    merged_df.to_csv(drive_save_path, index=False)
    print(f"✅ Predictions saved to: {drive_save_path}")

# Example usage:
# predict_new_data("path_to_model", "path_to_tokenizer", batch_size=16, device="cuda")

predict_new_data("finetuned_model/final_model", "finetuned_model/final_model", batch_size=32)

"""# topic modeling"""

file_path = 'results/predicted_results.csv'
result = pd.read_csv(file_path)

#result['time'] = result['time'].apply(lambda x: f"{x:.0f}")
result['time'] = result['time'].apply(lambda x: int(x))
result['time'][:5]

from datetime import datetime

# Convert to datetime
result['year'] = result['time'].apply(lambda x: datetime.fromtimestamp(x).year)
result['month'] = result['time'].apply(lambda x: datetime.fromtimestamp(x).month)
result['day'] = result['time'].apply(lambda x: datetime.fromtimestamp(x).day)

result.head()

result = result.dropna(subset = 'text')

label_counts = result["predicted_label"].value_counts()
label_counts

result.to_csv('results/updated_results.csv')

import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
text_data = result[result["predicted_label"] == 1]["text"].dropna().tolist()

text_combined = " ".join(text_data)

wordcloud = WordCloud(width=800, height=400, background_color="white").generate(text_combined)
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud for Texts with Predicted Label = 1")
plt.show()

"""## gensim-lda"""

import gensim
from gensim import corpora
from gensim.models.ldamodel import LdaModel
#from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import nltk

nltk.download('punkt')
#nltk.download('stopwords')
nltk.download('wordnet')

from spacy.lang.en.stop_words import STOP_WORDS

# Add your custom stop words to the default set
CUSTOM_STOP_WORDS = set(['know', 'yeah', 'got', 'd', 'girls',
                         'right', 'go', 'man', 'shit', "ain't",
                         'fuck', 'one', 'come', 'need', 'weight', 'loss'])
STOP_WORDS.update(CUSTOM_STOP_WORDS)


# Step 1: Preprocessing
def preprocess_text(text):

    lemmatizer = WordNetLemmatizer()

    # Tokenize, remove stopwords, and lemmatize
    tokens = word_tokenize(text.lower())
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word.isalpha() and word not in STOP_WORDS]
    return tokens

preprocessed_posts = [preprocess_text(post) for post in list(result['text'])]

# Step 2: Create Dictionary and Corpus
dictionary = corpora.Dictionary(preprocessed_posts)
corpus = [dictionary.doc2bow(post) for post in preprocessed_posts]

# Step 3: Apply LDA
lda_model = LdaModel(corpus, num_topics=10, id2word=dictionary, passes=10)

# Step 4: Get Topics for Each Post
topics_per_post = []
for post_bow in corpus:
    topic_probs = lda_model.get_document_topics(post_bow)
    dominant_topic = max(topic_probs, key=lambda x: x[1])
    topics_per_post.append(dominant_topic)

result['topic'] = topics_per_post

result.to_csv('results/updated_results.csv')

top_words_per_topic = []
for topic_id in range(10):
    top_words = lda_model.show_topic(topic_id, topn=20)  # Top 10 words for each topic
    top_words_dict = {
        "Topic": topic_id,
        "Top Words": ", ".join([word for word, _ in top_words])
    }
    top_words_per_topic.append(top_words_dict)

# Convert to a DataFrame
df_topics = pd.DataFrame(top_words_per_topic)

# Save to CSV
df_topics.to_csv("results/topics_top_words.csv", index=False)

# Display Topics for Each Post
for i, post in enumerate(text_data[:10]):
    topic_id, topic_prob = topics_per_post[i]
    topic_terms = lda_model.show_topic(topic_id, topn=10)
    topic_keywords = ", ".join([term for term, _ in topic_terms])
    print(f"Post: {post}\nDominant Topic: {topic_id} (Keywords: {topic_keywords})\n")

"""# exploratory"""

result = pd.read_csv('results/updated_results.csv')

result.head()

import matplotlib.pyplot as plt

# Step 1: Combine years, month, day into a single date column
result['date'] = pd.to_datetime(result[['year', 'month', 'day']])

# Step 2: Group by date and calculate counts of 0s and 1s
time_series = result.groupby(['date', 'predicted_label']).size().unstack(fill_value=0)

# Plot without markers
plt.figure(figsize=(10, 6))
plt.plot(time_series.index, time_series[0], label='Count of 0s')
plt.plot(time_series.index, time_series[1], label='Count of 1s')

# Customize the chart
plt.title('Time Series of Labels 0 and 1')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Resample data by week and calculate the sum for each week
weekly_data = time_series.resample('W').sum()

# Plot the smoother line chart
plt.figure(figsize=(10, 6))
plt.plot(weekly_data.index, weekly_data[0], label='Count of 0s')
plt.plot(weekly_data.index, weekly_data[1], label='Count of 1s')

# Customize the chart
plt.title('Smoothed Time Series of Labels 0 and 1 (Weekly Aggregation)')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Resample data by week and sum counts of 0s and 1s
weekly_data = time_series.resample('W').sum()

# Calculate the percentage of 0s for each week
weekly_data['percentage_1'] = (weekly_data[1] / weekly_data['total']) * 100

# Plot the percentage of 0s over time
plt.figure(figsize=(10, 6))
plt.plot(time_series.index, time_series['percentage_1'], label='% of 0s', color='blue')

# Customize the chart
plt.title('Percentage of 1s Over Time')
plt.xlabel('Date')
plt.ylabel('Percentage of 1s')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Define a threshold to remove outliers (e.g., percentages below 0 or above 100 are invalid)
threshold_min = 0
threshold_max = 90

# Filter the data to remove outliers
weekly_data_cleaned = weekly_data[(weekly_data['percentage_1'] >= threshold_min) &
                                  (weekly_data['percentage_1'] <= threshold_max)]

# Plot the cleaned data
plt.figure(figsize=(10, 6))
plt.plot(weekly_data_cleaned.index, weekly_data_cleaned['percentage_1'], label='% of 1s', color='blue')

# Customize the chart
plt.title('Weekly Percentage of 1s Over Time (Outliers Removed)')
plt.xlabel('Date')
plt.ylabel('Percentage of 1s')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

result['topic_num'] = result['topic'].apply(lambda x: x[1])

label_counts_1 = result[result['predicted_label']==1]['topic_num'].value_counts()
# Calculate the percentage for each label
label_percentage = (label_counts_1 / label_counts_1.sum()) * 100

# Print the percentages
print(label_percentage)

label_counts_0 = result[result['predicted_label']==0]['topic_num'].value_counts()
# Calculate the percentage for each label
label_percentage = (label_counts_0 / label_counts_0.sum()) * 100

# Print the percentages
print(label_percentage)

# try to match the following keywords
words = ['Mounjaro', 'Wegovy', 'Ozempic', 'Zepbound', 'Tirzepatide', 'semaglutide','Saxenda','Rybelsus','novo nordisk']

for word in words:
    result[word] = result['text'].str.contains(word, case=False).astype(int)

# Display the resulting DataFrame
print(result)

# mounjaro
import matplotlib.pyplot as plt

# Step 1: Combine years, month, day into a single date column
result['date'] = pd.to_datetime(result[['year', 'month', 'day']])

# Step 2: Group by date and calculate counts of 0s and 1s
time_series = result[result['Mounjaro']==1].groupby(['date', 'predicted_label']).size().unstack(fill_value=0)

# Plot without markers
plt.figure(figsize=(10, 6))
plt.plot(time_series.index, time_series[0], label='Count of 0s')
plt.plot(time_series.index, time_series[1], label='Count of 1s')

# Customize the chart
plt.title('Time Series of Labels 0 and 1')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Resample data by week and calculate the sum for each week
weekly_data = time_series.resample('W').sum()

# Plot the smoother line chart
plt.figure(figsize=(10, 6))
plt.plot(weekly_data.index, weekly_data[0], label='Count of 0s')
plt.plot(weekly_data.index, weekly_data[1], label='Count of 1s')

# Customize the chart
plt.title('Smoothed Time Series of Labels 0 and 1 (Weekly Aggregation)')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# wegovy
import matplotlib.pyplot as plt

# Step 1: Combine years, month, day into a single date column
result['date'] = pd.to_datetime(result[['year', 'month', 'day']])

# Step 2: Group by date and calculate counts of 0s and 1s
time_series = result[result['Wegovy']==1].groupby(['date', 'predicted_label']).size().unstack(fill_value=0)

# Plot without markers
plt.figure(figsize=(10, 6))
plt.plot(time_series.index, time_series[0], label='Count of 0s')
plt.plot(time_series.index, time_series[1], label='Count of 1s')

# Customize the chart
plt.title('Time Series of Labels 0 and 1')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()
# Resample data by week and calculate the sum for each week
weekly_data = time_series.resample('W').sum()

# Plot the smoother line chart
plt.figure(figsize=(10, 6))
plt.plot(weekly_data.index, weekly_data[0], label='Count of 0s')
plt.plot(weekly_data.index, weekly_data[1], label='Count of 1s')

# Customize the chart
plt.title('Smoothed Time Series of Labels 0 and 1 (Weekly Aggregation)')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Ozempic
import matplotlib.pyplot as plt

# Step 1: Combine years, month, day into a single date column
result['date'] = pd.to_datetime(result[['year', 'month', 'day']])
result['date'] = pd.to_datetime(result['date'])

# Step 2: Group by date and calculate counts of 0s and 1s
time_series = result[(result['Ozempic']==1)&(result['date']>= pd.Timestamp('2021-01-01'))].groupby(['date', 'predicted_label']).size().unstack(fill_value=0)

# Plot without markers
plt.figure(figsize=(10, 6))
plt.plot(time_series.index, time_series[0], label='Count of 0s')
plt.plot(time_series.index, time_series[1], label='Count of 1s')

# Customize the chart
plt.title('Time Series of Labels 0 and 1')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()
# Resample data by week and calculate the sum for each week
weekly_data = time_series.resample('W').sum()

# Plot the smoother line chart
plt.figure(figsize=(10, 6))
plt.plot(weekly_data.index, weekly_data[0], label='Count of 0s')
plt.plot(weekly_data.index, weekly_data[1], label='Count of 1s')

# Customize the chart
plt.title('Smoothed Time Series of Labels 0 and 1 (Weekly Aggregation)-Ozempic')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Calculate the percentage of 0s for each week
weekly_data['total'] = weekly_data[0] + weekly_data[1]
weekly_data['percentage_1'] = (weekly_data[1] / weekly_data['total']) * 100
# Define a threshold to remove outliers (e.g., percentages below 0 or above 100 are invalid)
threshold_min = 0
threshold_max = 90

# Filter the data to remove outliers
weekly_data_cleaned = weekly_data[(weekly_data['percentage_1'] >= threshold_min) &
                                  (weekly_data['percentage_1'] <= threshold_max)]

# Plot the cleaned data
plt.figure(figsize=(10, 6))
plt.plot(weekly_data_cleaned.index, weekly_data_cleaned['percentage_1'], label='% of 1s', color='blue')

# Customize the chart
plt.title('Weekly Percentage of 1s Over Time (Outliers Removed)')
plt.xlabel('Date')
plt.ylabel('Percentage of 1s')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Zepbound
import matplotlib.pyplot as plt

# Step 1: Combine years, month, day into a single date column
result['date'] = pd.to_datetime(result[['year', 'month', 'day']])

# Step 2: Group by date and calculate counts of 0s and 1s
time_series = result[result['Zepbound']==1].groupby(['date', 'predicted_label']).size().unstack(fill_value=0)

# Plot without markers
plt.figure(figsize=(10, 6))
plt.plot(time_series.index, time_series[0], label='Count of 0s')
plt.plot(time_series.index, time_series[1], label='Count of 1s')

# Customize the chart
plt.title('Time Series of Labels 0 and 1')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()
# Resample data by week and calculate the sum for each week
weekly_data = time_series.resample('W').sum()

# Plot the smoother line chart
plt.figure(figsize=(10, 6))
plt.plot(weekly_data.index, weekly_data[0], label='Count of 0s')
plt.plot(weekly_data.index, weekly_data[1], label='Count of 1s')

# Customize the chart
plt.title('Smoothed Time Series of Labels 0 and 1 (Weekly Aggregation)')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Calculate the percentage of 0s for each week
weekly_data['total'] = weekly_data[0] + weekly_data[1]
weekly_data['percentage_1'] = (weekly_data[1] / weekly_data['total']) * 100
# Define a threshold to remove outliers (e.g., percentages below 0 or above 100 are invalid)
threshold_min = 0
threshold_max = 90

# Filter the data to remove outliers
weekly_data_cleaned = weekly_data[(weekly_data['percentage_1'] >= threshold_min) &
                                  (weekly_data['percentage_1'] <= threshold_max)]

# Plot the cleaned data
plt.figure(figsize=(10, 6))
plt.plot(weekly_data_cleaned.index, weekly_data_cleaned['percentage_1'], label='% of 1s', color='blue')

# Customize the chart
plt.title('Weekly Percentage of 1s Over Time (Outliers Removed)')
plt.xlabel('Date')
plt.ylabel('Percentage of 1s')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# novo nordisk
import matplotlib.pyplot as plt

# Step 1: Combine years, month, day into a single date column
result['date'] = pd.to_datetime(result[['year', 'month', 'day']])
result['date'] = pd.to_datetime(result['date'])

# Step 2: Group by date and calculate counts of 0s and 1s
time_series = result[(result['novo nordisk']==1)&(result['date']>= pd.Timestamp('2021-01-01'))].groupby(['date', 'predicted_label']).size().unstack(fill_value=0)

# Plot without markers
plt.figure(figsize=(10, 6))
plt.plot(time_series.index, time_series[0], label='Count of 0s')
plt.plot(time_series.index, time_series[1], label='Count of 1s')

# Customize the chart
plt.title('Time Series of Labels 0 and 1')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()
# Resample data by week and calculate the sum for each week
weekly_data = time_series.resample('W').sum()

# Plot the smoother line chart
plt.figure(figsize=(10, 6))
plt.plot(weekly_data.index, weekly_data[0], label='Count of 0s')
plt.plot(weekly_data.index, weekly_data[1], label='Count of 1s')

# Customize the chart
plt.title('Smoothed Time Series of Labels 0 and 1 (Weekly Aggregation)-novo nordisk')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Calculate the percentage of 0s for each week
weekly_data['total'] = weekly_data[0] + weekly_data[1]
weekly_data['percentage_1'] = (weekly_data[1] / weekly_data['total']) * 100
# Define a threshold to remove outliers (e.g., percentages below 0 or above 100 are invalid)
threshold_min = 0
threshold_max = 90

# Filter the data to remove outliers
weekly_data_cleaned = weekly_data[(weekly_data['percentage_1'] >= threshold_min) &
                                  (weekly_data['percentage_1'] <= threshold_max)]

# Plot the cleaned data
plt.figure(figsize=(10, 6))
plt.plot(weekly_data_cleaned.index, weekly_data_cleaned['percentage_1'], label='% of 1s', color='blue')

# Customize the chart
plt.title('Weekly Percentage of 1s Over Time (Outliers Removed)')
plt.xlabel('Date')
plt.ylabel('Percentage of 1s')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Tirzepatide
import matplotlib.pyplot as plt

# Step 1: Combine years, month, day into a single date column
result['date'] = pd.to_datetime(result[['year', 'month', 'day']])
result['date'] = pd.to_datetime(result['date'])

# Step 2: Group by date and calculate counts of 0s and 1s
time_series = result[(result['Tirzepatide']==1)&(result['date']>= pd.Timestamp('2021-01-01'))].groupby(['date', 'predicted_label']).size().unstack(fill_value=0)

# Plot without markers
plt.figure(figsize=(10, 6))
plt.plot(time_series.index, time_series[0], label='Count of 0s')
plt.plot(time_series.index, time_series[1], label='Count of 1s')

# Customize the chart
plt.title('Time Series of Labels 0 and 1')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()
# Resample data by week and calculate the sum for each week
weekly_data = time_series.resample('W').sum()

# Plot the smoother line chart
plt.figure(figsize=(10, 6))
plt.plot(weekly_data.index, weekly_data[0], label='Count of 0s')
plt.plot(weekly_data.index, weekly_data[1], label='Count of 1s')

# Customize the chart
plt.title('Smoothed Time Series of Labels 0 and 1 (Weekly Aggregation)-Tirzepatide')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

# Calculate the percentage of 0s for each week
weekly_data['total'] = weekly_data[0] + weekly_data[1]
weekly_data['percentage_1'] = (weekly_data[1] / weekly_data['total']) * 100
# Define a threshold to remove outliers (e.g., percentages below 0 or above 100 are invalid)
threshold_min = 0
threshold_max = 90

# Filter the data to remove outliers
weekly_data_cleaned = weekly_data[(weekly_data['percentage_1'] >= threshold_min) &
                                  (weekly_data['percentage_1'] <= threshold_max)]

# Plot the cleaned data
plt.figure(figsize=(10, 6))
plt.plot(weekly_data_cleaned.index, weekly_data_cleaned['percentage_1'], label='% of 1s', color='blue')

# Customize the chart
plt.title('Weekly Percentage of 1s Over Time (Outliers Removed)')
plt.xlabel('Date')
plt.ylabel('Percentage of 1s')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()